JobBoard/Controllers/ApplicantsController.cs
using Microsoft.AspNetCore.Mvc;

namespace JobBoard.Controllers
{
    public class ApplicantsController : Controller
    {
        private readonly JobBoardContext jobBoardContext;

        public ApplicantsController(JobBoardContext jobBoardContext)
        {
            this.jobBoardContext = jobBoardContext;
        }
        public async Task<IActionResult> Index(string username)
        {
            Company company = jobBoardContext.companies.FirstOrDefault(x=>x.UserName==username);
            if (company==null )
            {
                return View("error");
            }

            List<JobSeeker> jobSeeker = jobBoardContext.jobSeekers.Include(x=>x.Job).Where(x=>x.CompanyId==company.Id).Where(x=>x.IsCompleted==false).OrderByDescending(x=>x.Id).ToList();
            return View(jobSeeker);
        }

        public IActionResult Accept(int id)
        {
            JobSeeker jobSeeker=jobBoardContext.jobSeekers.FirstOrDefault(x=>x.Id==id);
            if (jobSeeker==null) { return View("error"); }

            Job job = jobBoardContext.Jobs.FirstOrDefault(x => x.Id == jobSeeker.JobId);
            if (job==null)
            {
                return View("error");
            }
            if (job.Vacancy>0)
            {
            job.Vacancy -= 1;
            }

            if (job.Vacancy==0)
            {
                job.IsFull = true;
            }

            jobSeeker.IsCompleted = true;


            jobBoardContext.SaveChanges();

            return RedirectToAction("Index","home");
        }

        public IActionResult Delete(int id) 
        {
        
             JobSeeker jobSeeker=jobBoardContext.jobSeekers.FirstOrDefault(x=>x.Id== id);    
            if (jobSeeker==null)  return View("error");
            jobBoardContext.jobSeekers.Remove(jobSeeker);
            jobBoardContext.SaveChanges();
            return RedirectToAction("index");
        }


    }
}

JobBoard/Views/Applicants/Index.cshtml
@model List<JobSeeker>
@{
    ViewData["Title"] = "Index";
    int count = 0;
}

 <section class="section-hero overlay inner-page bg-image" style="background-image: url('../assets/images/hero_1.jpg');" id="home-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                <h1 class="text-white font-weight-bold">Your Applicants</h1>
                        <div class="custom-breadcrumbs">
                            <a asp-action="index" asp-controller="home">Home</a> 
                        </div>
                    </div>
                </div>
            </div>
        </section>




<section class="container" style="margin-bottom:300px;margin-top:100px" >
    <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Job</th>
      <th scope="col">Fullname</th>
      <th scope="col">Email</th>
      <th scope="col">Cv</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
      @foreach (var item in Model)
            {
                count++;
                <tr>
      <th scope="row">@count</th>
      <td><a asp-action="details" asp-controller="job" asp-route-id="@item.JobId">@item.Job.Title</a></td>
      <td>@item.FullName</td>
      <td>@item.Email</td>
      <td><a href="~/uploads/member/cv/@item.Cv">Show CV</a></td>
      <td>
                        <a asp-action="Accept" asp-controller="Applicants" asp-route-id="@item.Id" class="QebulEt text-success"> <i class="bi bi-check-circle-fill"></i> </a>

                        <a asp-action="delete" asp-controller="Applicants" asp-route-id="@item.Id" class=" deletebtn text-danger"> <i class="bi bi-x-octagon-fill"></i>  </a>
      </td>
    </tr>
            }
  </tbody>
</table>
</section>

<script>

    let applybtn = document.getElementById("QebulEt");
applybtn.addEventListener("click", function (e) {
    e.preventDefault;
        alert("You have already accepted it");
})


   

</script>